topic:
  name: users
  partitions-num: 3
  replication-factor: 3
server:
  port: 9080
spring:
  cloud:
    stream:
      default: 
         producer: 
          useNativeEncoding: true
         consumer:  
          useNativeEncoding: true     
      bindings:
        input:
          destination: users
          content-type: application/*+avro
          group: simple-consumer
          
        output:
          destination: users
          content-type: application/*+avro
      kafka:
          binder:        
           producer-properties:
             key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
             value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
             schema.registry.url: https://psrc-lgy7n.europe-west3.gcp.confluent.cloud 
            
           consumer-properties:
             key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
             value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
             schema.registry.url: https://psrc-lgy7n.europe-west3.gcp.confluent.cloud
             specific.avro.reader: true